import { Topbar } from "@/components/dashboard/topbar";
import { Card, CardHeader, CardTitle } from "@/components/ui/card";
import { WellbeingRing } from "@/components/dashboard/wellbeing-ring";
import { ScreenTimeChart } from "@/components/dashboard/screen-time-chart";
import { MoodChart } from "@/components/dashboard/mood-chart";
import { RiskAlertCard } from "@/components/dashboard/risk-alert-card";
import { Badge } from "@/components/ui/badge";
import { child, riskAlerts, appUsage, weeklyReport } from "@/lib/mock-data";
import Link from "next/link";

export default function OverviewPage() {
  const topApps = appUsage.slice(0, 3);

  return (
    <div>
      <Topbar title={`Good evening 👋`} subtitle={`Here's how ${child.name} is doing this week.`} />

      <div className="grid gap-5 lg:grid-cols-3">
        <Card className="flex flex-col items-center justify-center lg:col-span-1">
          <CardHeader className="w-full">
            <CardTitle>Digital Wellbeing Score</CardTitle>
          </CardHeader>
          <WellbeingRing score={child.wellbeingScore} trend={child.wellbeingTrend} />
          <p className="mt-4 max-w-xs text-center text-xs text-muted">
            Calculated from sleep, night usage, education vs. gaming balance, and mood signals.
          </p>
        </Card>

        <Card className="lg:col-span-2">
          <CardHeader>
            <CardTitle>Screen Time This Week</CardTitle>
            <Link href="/dashboard/screen-time" className="text-xs text-primary hover:underline">
              View details →
            </Link>
          </CardHeader>
          <ScreenTimeChart />
        </Card>
      </div>

      <div className="mt-5 grid gap-5 lg:grid-cols-3">
        <Card className="lg:col-span-1">
          <CardHeader>
            <CardTitle>Mood Trend</CardTitle>
            <Link href="/dashboard/mood" className="text-xs text-primary hover:underline">
              Journal →
            </Link>
          </CardHeader>
          <MoodChart />
        </Card>

        <Card className="lg:col-span-1">
          <CardHeader>
            <CardTitle>Top Apps</CardTitle>
            <Link href="/dashboard/app-usage" className="text-xs text-primary hover:underline">
              All apps →
            </Link>
          </CardHeader>
          <div className="flex flex-col gap-3">
            {topApps.map((app) => (
              <div key={app.app} className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <span className="h-2.5 w-2.5 rounded-full" style={{ backgroundColor: app.color }} />
                  <span className="text-sm">{app.app}</span>
                </div>
                <div className="text-right">
                  <p className="text-sm font-medium">{app.time}</p>
                  <p className="text-xs text-muted">{app.percentage}%</p>
                </div>
              </div>
            ))}
          </div>
        </Card>

        <Card className="lg:col-span-1">
          <CardHeader>
            <CardTitle>Top Risk Alert</CardTitle>
            <Link href="/dashboard/alerts" className="text-xs text-primary hover:underline">
              All alerts →
            </Link>
          </CardHeader>
          <RiskAlertCard {...riskAlerts[0]} />
        </Card>
      </div>

      <Card className="mt-5">
        <CardHeader>
          <CardTitle>AI Weekly Summary</CardTitle>
          <Badge color="var(--secondary)">Generated by AI Risk Engine</Badge>
        </CardHeader>
        <p className="text-sm leading-relaxed text-muted">{weeklyReport.summary}</p>
        <div className="mt-4 grid gap-4 sm:grid-cols-2">
          <div>
            <p className="mb-2 text-xs font-semibold text-accent">Wins</p>
            <ul className="space-y-1 text-sm text-muted">
              {weeklyReport.wins.map((w) => (
                <li key={w}>• {w}</li>
              ))}
            </ul>
          </div>
          <div>
            <p className="mb-2 text-xs font-semibold text-warning">Watch-outs</p>
            <ul className="space-y-1 text-sm text-muted">
              {weeklyReport.watchouts.map((w) => (
                <li key={w}>• {w}</li>
              ))}
            </ul>
          </div>
        </div>
      </Card>
    </div>
  );
}
